### ISSUE TITLE
Ensure that the SDK supports apps switching between different lightwalletd servers

### ISSUE THREAD

**Issue by str4d** [Electric-Coin-Company/zcash-android-wallet-sdk#1393]
This might be trivially closed if the answer is "just stop and restart the Synchronizer", but we should confirm that this works, and if it doesn't then make SDK changes to enable it.

**Comment by HonzaR** [comment]
Additional information: https://github.com/Electric-Coin-Company/zcash-swift-wallet-sdk/issues/1153
