### ISSUE TITLE
test and adopt ZIP 320 in the Android SDK

### ISSUE THREAD

**Issue by true-jared** [Electric-Coin-Company/zcash-android-wallet-sdk#1535]
- test the implementation by executing testing transactions to a TEX address
- validate the implementation
- trubleshoot any issues with the Core Team if necessary
- adopt ZIP 320 in the Android SDK
- integrate ZIP 320 in the Zashi wallet

**Comment by true-jared** [comment]
Looks like I cannot close this task @HonzaR, can you try?

**Comment by HonzaR** [comment]
@true-jared It seems closed to me now.
