### ISSUE TITLE
Finish multi-account support

### ISSUE THREAD

**Issue by str4d** [Electric-Coin-Company/zcash-android-wallet-sdk#1634]
This issue can be closed once we can reliably use the SDK to run a wallet containing multiple independent UFVKs (that may not be from the same seed, or for which we might not even know the seed).

**Comment by HonzaR** [comment]
Removing https://github.com/Electric-Coin-Company/zashi-android/pull/410 as a prerequisite to this for the upcoming release, as discussed internally.

**Comment by HonzaR** [comment]
Closing as done as part of #1661
