### ISSUE TITLE
After upgrading your SDK to 2.2.6 our app size grow more than 19mb

### ISSUE THREAD

**Issue by rafaelekol** [Electric-Coin-Company/zcash-android-wallet-sdk#1642]
Recently we updated your SDK in Unstoppable Wallet, and our apk size grow more than 19mb. And its now a problem for us.
Check the screenshot
<img width="658" alt="Screenshot 2024-11-25 at 09 57 20" src="https://github.com/user-attachments/assets/880b6ac1-fe22-4db8-97a8-f1af07d21eb2">

**Comment by HonzaR** [comment]
Hi @rafaelekol. Thanks for reaching out. The size of the SDK release v2.2.6 should be very similar to the size of v2.2.5. See Maven Central for comparison: https://repo1.maven.org/maven2/cash/z/ecc/android/zcash-android-sdk/.

**Comment by str4d** [comment]
What version SDK did you update from?

**Comment by HonzaR** [comment]
That's a valid question. However, the SDK size has grown relatively slowly over the last year.

**Comment by rafaelekol** [comment]
@str4d We updated from `2.1.1`. And since we build apk with all architectures, the increase was significant

**Comment by str4d** [comment]
In an upgrade from 2.1.1 to 2.2.6, you would have seen the size increase from us starting to bundle Tor in 2.2.0. The `libtor` binaries in your screenshot look like they add up to most of the observed increase.

We aren't going to remove Tor support or make it optional, but I would be interested to know what exactly goes into `libtor` and whether there's any functionality that we will never need that could potentially be feature flagged off in Rust.

**Comment by rafaelekol** [comment]
Our wallet also using Tor library for secure connections. It seems that with latest Zcash our app gets 2 libtor.so.
