### ISSUE TITLE
Make it more difficult to use the testnet SDK with mainnet LWD

### ISSUE THREAD

**Issue by gmale** [Electric-Coin-Company/zcash-android-wallet-sdk#180]
It is still technically possible to connect to a server on the wrong chain. In the past, this was prevented by letting the SDK choose the server by default but, nowadays, developers are expected to run their own servers. This means that the SDK needs to be more defensive in the way that it manages data.

Criteria:
- testnet checkpoints cannot be used with mainnet lightwalletd servers and vice-versa.
- if the SDK is in testnet mode it rejects servers that are on the wrong chain
- developers can override this behavior with error handler callbacks
- [optional] expose properties in the SDK that allow the developer to inspect whether the local data is mainet and whether the server is mainnet

Test cases:
- create a wallet with a testnet checkpoint, then point it to a mainnet server
- create a wallet with a mainnet checkpoint, then point it to a testnet server
- sync a wallet on mainnet, then relaunch the app, pointing to testnet
- sync a wallet on testnet, then relaunch the app, pointing to mainnet

**Comment by pacu** [comment]
I think this is done

**Comment by HonzaR** [comment]
This is ensured by `CompactBlockProcessor.verifySetup`. And the new server switching logic, as defined in #1406, adds `Synchronizer.validateServerEndpoint`.
