### ISSUE TITLE
Fix the balance display: Show expected change as part of balance

### ISSUE THREAD

**Issue by gmale** [Electric-Coin-Company/zcash-android-wallet-sdk#238]
As a librustzcash user, I'd like more fine-grained information about balance so that I can easily include expected change in the reported total balance.

This would address the persistently reported [issue that the change display is confusing](https://github.com/zcash/zcash-android-wallet/issues/76#issuecomment-649103622).

Criteria:
* functions exist that allow wallet developers to distinguish between the balance of incoming funds vs. expected change of unconfirmed outbound transactions
* getting the balance never shows zero unless the user actually has no funds
* test: create a wallet with one note, spend a fraction of that note and 1 block later, the reported balance should not be zero

Implementation details:
* I wrote quick, overly simplified, [example code here](https://github.com/zcash/librustzcash/issues/249#issuecomment-870979067)
    * this is an oversimplification because it does not address the root cause
    * however, it might be enough of a bandaid to improve the user experience
* this issue is rooted in the sqlite crate not tracking unmined transactions (the mempool) 
    * the SDK compensates by using the PendingTransaction.db that the Rust layer has no knowledge of
    * we should fix the root problem by [getting rid of the pending transaction database](https://github.com/zcash/zcash-android-wallet-sdk/issues/239)

**Comment by nuttycom** [comment]
This is related to #1170. Adding this to the Spend-before-Sync milestone because it should be resolved in the process of deploying spend-before-sync.

**Comment by HonzaR** [comment]
Closing as implemented within #1380 and #1386.
