### ISSUE TITLE
Add dependency locking for Gradle plugins

### ISSUE THREAD

**Issue by ccjernigan** [Electric-Coin-Company/zcash-android-wallet-sdk#314]
**What is your feature request?**
We should enable dependency locking for Gradle plugins, to ensure that builds are consistent if transitive dependencies do not pin to exact versions

**Comment by Milan-Nerevar** [comment]
@HonzaR this item looks like it's done already

**Comment by HonzaR** [comment]
That's correct. Thanks for pointing this out. Closing.
