### ISSUE TITLE
Update NDK to 24.0.7856742

### ISSUE THREAD

**Issue by ccjernigan** [Electric-Coin-Company/zcash-android-wallet-sdk#317]
Once #423 is implemented, we can update to NDK 23.

Before updating the NDK version, be aware of information in the https://github.com/zcash/zcash-android-wallet-sdk/issues/539.

**Comment by HonzaR** [comment]
Before updating the NDK version, be aware of information in the https://github.com/zcash/zcash-android-wallet-sdk/issues/539.
