### ISSUE TITLE
Add public API to configure debug logging

### ISSUE THREAD

**Issue by ccjernigan** [Electric-Coin-Company/zcash-android-wallet-sdk#591]
## Is your feature request related to a problem? Please describe.
For debugging, sometimes we need to enable logging in the SDK.  Currently this can be done by `cash.z.ecc.android.sdk.internal.Twig.enabled(true)`.  This is non-obvious for someone looking at the API and Twig is an internal API.

## Describe the solution you'd like
Add a public API that makes it easy to enable logging.

The exact implementation may depend on decisions made for #482.

**Comment by HonzaR** [comment]
Closing as still not implemented. Will be replaced with https://github.com/Electric-Coin-Company/zcash-android-wallet-sdk/issues/1435
