### ISSUE TITLE
Removed ConfirmedTransaction

### ISSUE THREAD

**Issue by gasstan** [Electric-Coin-Company/zcash-android-wallet-sdk#752]
### Describe the issue

ConfirmedTransaction was removed from the latest SDK version. ChangeLog is not mentioning this, so it is not clear what can it be replaced with.

This is causing issues in the old wallet app. It appears that it could be replaced with PendingTransaction however this is not the case in all instances

**Comment by ccjernigan** [comment]
ConfirmedTransaction is replaced by TransactionOverview.

Memos must be queried separately now.
