### ISSUE TITLE
Add Support for ZIP 317 Fees in Public API

### ISSUE THREAD

**Issue by ccjernigan** [Electric-Coin-Company/zcash-android-wallet-sdk#776]
## Is your feature request related to a problem? Please describe.
ZIP 317 adds variable fees.  The SDK has been mostly implemented assuming fixed fees.  The underlying librustzcash supports ZIP 317 but work needs to be done in the public API to make variable fees better supported.

## Describe the solution you'd like
 - Refactor the current fixed fee constant in the SDK so that clients know it isn't always going to be the fee amount
 - Update the demo app to support ZIP 317 fees
 - Documentation: https://github.com/zcash/zips/blob/main/zip-0317.rst

**Comment by str4d** [comment]
Once the SDK's API is updated as appropriate, the final step is to change this constant to `true`:
https://github.com/zcash/zcash-android-wallet-sdk/blob/1a0508f57dfa6eec68668f4705990f59f62ff3c5/backend-lib/src/main/java/cash/z/ecc/android/sdk/internal/jni/RustBackend.kt#L362
