### ISSUE TITLE
Improve Synchroniser initialisation error

### ISSUE THREAD

**Issue by gasstan** [Electric-Coin-Company/zcash-android-wallet-sdk#782]
### Describe the issue

When Initialising the Synchroniser without providing the seed, 
Sdk throws NoAccountError. 

#### If so, please list the steps to reproduce below:
1. Initialise synchroniser as follows: 
```
Synchronizer.new(
            context = DependenciesHolder.provideAppContext(),
            zcashNetwork = zcashNetwork,
            alias = alias,
            lightWalletEndpoint = lightWalletEndpoint,
            seed = null,
            birthday = birthday
        )
```
2. call synchroniser.start()

### Expected behaviour

Sdk should throw `SeedRequired` error instead

**Comment by str4d** [comment]
I noticed this bug independently today and investigated.
- `SeedRequired` was introduced in #717, merged October 6 2022.
- #739 was then merged on October 19 2022; it deleted `PagedTransactionRepository.kt` where `SeedRequired` was being thrown, and didn't replicate the logic in `DerivedDataDb.kt`.
- SDK version 1.11.0-beta01 was released January 9 2023.

So AFAICT the correct logic never made it into a release.
