### ISSUE TITLE
Don’t Crash Demo App on Invalid Address

### ISSUE THREAD

**Issue by ccjernigan** [Electric-Coin-Company/zcash-android-wallet-sdk#800]
## Is your feature request related to a problem? Please describe.
Robo tests aren’t able to complete because the demo app doesn’t handle failed validation of addresses.

## Describe the solution you'd like
Instead of crashing, display an indicator that the address is invalid.

**Comment by HonzaR** [comment]
Closing as related to the old demo app version.
