### ISSUE TITLE
Slow addresses providing

### ISSUE THREAD

**Issue by HonzaR** [Electric-Coin-Company/zcash-android-wallet-sdk#846]
### Describe the issue
This is a followup for the https://github.com/zcash/zcash-android-wallet-sdk/pull/830.

I've noticed there in the new Compose Get Addresses screen following: The SDK provides addresses for the new Get Addresses screen very slowly. It may be related to the latest change in which we use Flow in this mechanism, which emits addresses with sync status change and it's very slow with Mainnet. You can even make it worst with making the networking slower with related device developers option. And I can confirm that the addresses are provided by the SDK immediately with device with connection turned off, and thus no syncing at the moment. But it's just a guess.

**Comment by Milan-Cerovsky** [comment]
@HonzaR I cannot reproduce this as the addresses load up fast, even with slow network

**Comment by HonzaR** [comment]
Yep, this issue seems to be resolved by some of the previous logic changes. I'm closing it. Thank you.
