### ISSUE TITLE
Delete transaction cancellation code

### ISSUE THREAD

**Issue by ccjernigan** [Electric-Coin-Company/zcash-android-wallet-sdk#876]
## Is your feature request related to a problem? Please describe.
Transaction cancellation was removed from the public API #861, but some internals still exist.

## Describe the solution you'd like
Remove the internal implementation details for transaction cancellation, as this implementation is not reliable.  E.g.
 - TransactionManager.cancel
 - PendingTransactionEntity.isCanceled()
etc.

**Comment by HonzaR** [comment]
Closing as already done in some of the previous refactorings
