### ISSUE TITLE
Fix compatibility with newer versions of Rust

### ISSUE THREAD

**Issue by ccjernigan** [Electric-Coin-Company/zcash-android-wallet-sdk#958]
### Describe the issue
This is a followup for #954.

#### If so, please list the steps to reproduce below:
1. `brew install rustup`
1. `rustup-init`
1. `rustup install 1.68.2`
1. `rustup default 1.68.2`
2. `rustup target add armv7-linux-androideabi aarch64-linux-android i686-linux-android x86_64-linux-android`
3. `./gradlew assemble`

### Expected behaviour
Build succeeds

### Actual behavior + errors
Build fails. See log here https://github.com/zcash/zcash-android-wallet-sdk/actions/runs/4542345259/jobs/8005652057

### Any extra information that might be useful in the debugging process.
Note that when fixing this issue, be sure to update the Setup.md and the setup.yml to reflect this has been fixed.

**Comment by str4d** [comment]
Closed by #1346.
